openapi: 3.0.0
info:
  title: Favorite API
  version: 1.0.0
  description: API pour gérer les favoris avec json-server
servers:
  - url: http://localhost:3001/api
paths:
  /favorites:
    get:
      summary: Récupère tous les favoris
      responses:
        '200':
          description: Liste de favoris
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
                    typeId:
                      type: integer
    post:
      summary: Ajoute un favori
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                typeId:
                  type: integer
      responses:
        '201':
          description: Favori ajouté
  /favorites/{id}:
    delete:
      summary: Supprime un favori par ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID du favori
      responses:
        '200':
          description: Favori supprimé
